POST http://localhost:6969/profile/Madhav1
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiJ9.TWFkaGF2.3WKIvJHsN0ZsEOGYUIMW7i2PpgZiuTm8uKiWn5RAu5M

{
  "name": "Madhav1",
  "money": 1200
}
// note: do not add a comma after the last json entry
// its not gonna end well...


// change type to log_in to login in /join
// change type to sign_up to signup in /join

// accesstoken : eyJhbGciOiJIUzI1NiJ9.aG9taWU.t-Q1NKB9kfL2xjrkO4vx1DTvnahrgKxIcHVTh-1rUvU