GET http://localhost:6969/profile/Madhav1
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiJ9.TWFkaGF2MQ.Qmihcnp0bb0wQaQZBwmHBfLBDv20HzOK7f-2zoeQw_E

{
  "name": "Madhav1",
  "money": 1200
}
// note: do not add a comma after the last json entry
// its not gonna end well...


// change type to log_in to login in /join
// change type to sign_up to signup in /join

// accesstoken (Madhav) : eyJhbGciOiJIUzI1NiJ9.aG9taWU.t-Q1NKB9kfL2xjrkO4vx1DTvnahrgKxIcHVTh-1rUvU
// accesstoken (Madhav1) : eyJhbGciOiJIUzI1NiJ9.TWFkaGF2MQ.Qmihcnp0bb0wQaQZBwmHBfLBDv20HzOK7f-2zoeQw_E